name: Self-hosted runner (benchmark)

on:
  schedule:
    - cron: "17 2 * * *"
  workflow_call:

env:
  HF_HOME: /mnt/cache
  TF_FORCE_GPU_ALLOW_GROWTH: true


jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-22.04
    steps:
      - name: Benchmark (daily)
        if: github.event_name == 'schedule'
        run: |
          echo Hello

      - name: Benchmark (merged to main event)
        if: github.event_name == 'workflow_run'
        run: |
          echo Hello2
