name: Self-hosted runner (scheduled)


on:
  repository_dispatch:
  schedule:
    - cron: "17 2 * * *"
  push:
    branches:
      - test-ci-1

jobs:
  deepspeed-ci:
    name: DeepSpeed CI
    #change repo to allow different branch
    uses: huggingface/hf-workflows/.github/workflows/transformers-test.yml@test-ci  
    with:
      job: run_all_tests_torch_cuda_extensions_gpu
      slack_report_channel: "#transformers-ci-daily-deepspeed"
    secrets: inherit
